// <auto-generated />
using HillsModelManager.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HillsModelManager.Migrations
{
    [DbContext(typeof(TrainDBContext))]
    partial class TrainDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("HillsModelManager.Models.TrainDataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainData")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrainDatasets");
                });
#pragma warning restore 612, 618
        }
    }
}
